Add OnPlayerStreamIn.md (ID) OnPlayerStreamOut.md (ID) OnPlayerStateChange (ID) OnPlayerTakeDamage (ID)
openmultiplayer/web pull request #101
Opened 2020-12-25 13:21 UTC by AthallahDzaki

Tolong Di Koreksi Bos :smile:

2020-12-27 03:48 UTC, Eiikirin requested changes
Ada beberapa yang kurang tepat, coba di perbaiki lagi.

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerStateChange.md
> +title: OnPlayerSpawn
Title salah.

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerStateChange.md
> +    if (oldstate == PLAYER_STATE_ONFOOT && newstate == PLAYER_STATE_DRIVER) // Player entered a vehicle as a driver
Komentar belum diterjemahkan

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerStreamIn.md
> +---
Coba lihat contoh ini: https://github.com/openmultiplayer/web/blob/master/docs/translations/id/scripting/callbacks/OnActorStreamIn.md

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerStreamOut.md
> +---
Coba lihat contoh ini: https://github.com/openmultiplayer/web/blob/master/docs/translations/id/scripting/callbacks/OnActorStreamIn.md

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerStreamOut.md
> +<VersionWarnID name='Callback' version='SA-MP 0.3a' />
Coba dibaca: 
https://github.com/openmultiplayer/wiki/issues/263#issuecomment-720026425

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerTakeDamage.md
> +<VersionWarn name='callback' version='SA-MP 0.3d' />
Coba dibaca:
https://github.com/openmultiplayer/wiki/issues/263#issuecomment-720026425

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerStreamIn.md
> +// Tidak Ada
Tidak perlu pakai //tidak ada

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerStreamOut.md
> +// Tidak Ada
Tidak perlu pakai //tidak ada

2020-12-27 03:48 UTC, Eiikirin commented on docs/translations/id/scripting/callbacks/OnPlayerTakeDamage.md
> +// Tidak Ada
Tidak perlu pakai //tidak ada

2020-12-27 04:39 UTC, AthallahDzaki commented
@Eiikirin https://github.com/openmultiplayer/web/blame/master/docs/translations/id/scripting/callbacks/OnActorStreamOut.md#L15 coba cek salah Translate kak

2021-01-01 18:07 UTC, Eiikirin commented
Eh kok malah edit komen ya akwoakwoakw

2021-01-01 18:08 UTC, Eiikirin commented
fokus sama PR, gak usah kemana²

2021-01-01 18:19 UTC, Eiikirin commented
[MERGED] to #121

2021-01-01 18:19 UTC, closed without merging