Create OnNPCDisconnect.md
openmultiplayer/web pull request #1019
Opened 2024-07-24 15:43 UTC by Fede5432

ES language

2024-07-24 15:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/web?pullRequest=1019) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/web?pullRequest=1019) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/web?pullRequest=1019) it.</sub>

2024-07-25 16:31 UTC, adib-yg requested changes
`docs/translations/es/scripting/callbacks/OnNPCDisconnect.md/OnNPCDisconnect.md`

Please correct the file path.

2024-07-26 23:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/web?pullRequest=1019) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/web?pullRequest=1019) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/web?pullRequest=1019) it.</sub>

2024-07-26 23:18 UTC, Fede5432 commented
done

2024-07-27 22:07 UTC, adib-yg requested changes

2024-07-27 22:07 UTC, adib-yg commented on docs/translations/es/scripting/callbacks/OnNPCDisconnect.md
> +título: OnNPCDisconnect
```suggestion
title: OnNPCDisconnect
```

2024-07-27 22:07 UTC, adib-yg commented on docs/translations/es/scripting/callbacks/OnNPCDisconnect.md
> +descripción: Este callback se llama cuando un NPC se desconecta del servidor.
```suggestion
description: Este callback se llama cuando un NPC se desconecta del servidor.
```

2024-07-27 22:08 UTC, adib-yg approved these changes

2024-07-27 22:08 UTC, merged