Restore SA-MP objects list
openmultiplayer/web pull request #426
Opened 2021-10-04 13:07 UTC by NexiusTailer

Samp objects list is restored in this PR:
It is return of information from old commits, when the wiki had its own lists in addition to just a link to a third-party resource. I think this not be removed again, as there need to be at least something, if any link become dead someday. Also old info contains images, but as I've checked they are ok and available now like before.

2021-10-04 15:46 UTC, Southclaws requested changes
Looks good, thanks!

Just a couple of minor grammar changes.

2021-10-04 15:46 UTC, Southclaws commented on docs/scripting/resources/samp_objects.md
> +description: This page has the information about the objects added in SA-MP
```suggestion
description: This page contains a list of the custom objects added by SA-MP.
```

2021-10-04 15:46 UTC, Southclaws commented on docs/scripting/resources/samp_objects.md
>  sidebar_label: SAMP Objects
```suggestion
sidebar_label: SA-MP Objects
```

2021-10-04 15:46 UTC, Southclaws commented on docs/scripting/resources/samp_objects.md
> +List of all objects
```suggestion
```

Unnecessary as the page title already tells you this.

2021-10-05 21:11 UTC, NexiusTailer commented
Sorry, but I deleted that branch of my forked repo and now there are problems with any additions to this pull request :/
I know it turned out pretty stupid, but creating a new fork won't change the situation now.

Regarding the proposed changes, I agree with each of those and would be happy to correct every case. Maybe I should create another PR after this, or this time with both current opened pull requests, could you fix all the inconsistencies you found with the next commit? I would be grateful anyway.

2021-10-09 12:16 UTC, Southclaws commented
That's fine I'll just merge this as-is and you can then make a new PR with the minor changes, thanks!

2021-10-09 12:16 UTC, merged