Added indonesia language in some function
openmultiplayer/web pull request #556
Opened 2022-02-19 12:27 UTC by deknaa

2022-02-19 12:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/web?pullRequest=556) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/web?pullRequest=556) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/web?pullRequest=556) it.</sub>

2022-02-19 18:13 UTC, Se8870 requested changes
Hallo, terimakasih sudah berkontribusi kedalam open.mp project. Disini saya akan review pr ini untuk di di perbharui kembali. 

Ada  beberapa hal yang dirasa harus diganti, seperti text yang mempunyai simbol `##` ikut di terjemahkan juga kedalam bahasa indonesia kecuali `## Returns`.

Dan ada juga beberapa komentar yang sudah saya berikan disini.

2022-02-19 18:13 UTC, Se8870 commented on docs/translations/id/scripting/function/ApplyAnimation.md
> +Apply an animation to a player.
Masih belum di translate ke bahasa indonesia

2022-02-19 18:13 UTC, Se8870 commented on docs/translations/id/scripting/function/GetPlayerMoney.md
> +Retrieves the amount of money a player has.
Yang ini juga masih belum di translate ke bahasa indonesia

2022-02-19 18:13 UTC, Se8870 commented on docs/translations/id/scripting/function/GetPlayerMoney.md
> +   format(string, sizeof(string), "Uang anda: $%i.", GetPlayerMoney(playerid));
Lebih baik text nya diisi seperti: `"Uang anda senilai: $%i"`

2022-02-19 18:13 UTC, Se8870 commented on docs/translations/id/scripting/function/GetPlayerMoney.md
> +| playerid | ID dari pemain yang akan diambil uang nya |
Alangkah baiknya di terjemahkan seperti ini: `ID dari pemain yang ingin dilihat uang nya`

2022-02-19 18:38 UTC, deknaa commented
Baik, akan saya perbaharui. Terimakasih atas masukannya.

2022-02-20 02:07 UTC, deknaa commented on docs/translations/id/scripting/function/ApplyAnimation.md
> +Apply an animation to a player.
Saya sudah memperbaharui nya, apakah perubahan nya sudah terlihat?

2022-02-20 09:26 UTC, Se8870 approved these changes

2022-03-19 07:07 UTC, merged

2022-03-19 07:07 UTC, Southclaws commented
Thanks for your contribution and thanks Se8870 for reviewing!