Add UID with correct author.
openmultiplayer/web pull request #618
Opened 2022-05-04 14:51 UTC by Y-Less

I added open.mp/uid, to allow you to generate a component UID easily.

My original plan was to just have a very very basic page with only the UID and nothing else, but I'm not sure how to do that easily in next.js. It would be nice in the future to have some facility to do that for other tools in the future though @Southclaws.

2022-05-04 16:05 UTC, leonardssh commented
I try to run the next app to see if it works as it should, but it throws an error.
```
ReferenceError: self is not defined
```
![image](https://user-images.githubusercontent.com/35312043/166722754-1d7bfaf4-733d-4c6e-a754-5f4cd74b8126.png)

I think we can't use the crypto module in the client, as it's built-in NodeJS module. Don't you think we could use a library like [uuid](https://www.npmjs.com/package/uuid)?

Reference: https://stackoverflow.com/a/71852390

2022-05-04 16:07 UTC, leonardssh commented
Apparently, it's a NextJS problem, it can't detect the `self` object

2022-05-04 16:47 UTC, leonardssh requested changes

2022-05-04 16:47 UTC, leonardssh commented on frontend/src/pages/uid.tsx
> +      var a = new Uint8Array(n);
Use `const` instead of `var`.
```suggestion
      const a = new Uint8Array(n);
```

2022-05-04 16:47 UTC, leonardssh commented on frontend/src/pages/uid.tsx
> +    return require("crypto").randomBytes as (n: number) => Uint8Array;
Disable eslint `@typescript-eslint/no-var-requires`.
```suggestion
    return require("crypto").randomBytes as (n: number) => Uint8Array; // eslint-disable-line @typescript-eslint/no-var-requires
```

2022-05-04 16:47 UTC, leonardssh commented on frontend/src/pages/uid.tsx
> +      <NextSeo title="Downloads" />
```suggestion
      <NextSeo title="UID Generator" />
```

2022-05-04 16:47 UTC, leonardssh commented on frontend/src/pages/uid.tsx
> +          */}
Useless code
```suggestion
```

2022-05-04 16:47 UTC, leonardssh commented on frontend/src/pages/uid.tsx
> +          */}
Useless code
```suggestion
```

2022-05-05 10:39 UTC, Southclaws commented
Keep it server side rendered - generate the UID in the getServerSideProps and propagate it to the page via props.

2022-05-05 12:14 UTC, merged