Added Indonesia Translation (with some additions) in some pages.
openmultiplayer/web pull request #693
Opened 2023-01-17 15:46 UTC by GNZTMPZ

I'll brief what's changed, or just track the commit to see what's changed. (still wip though, do not merge)

2023-01-17 15:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/web?pullRequest=693) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/web?pullRequest=693) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/web?pullRequest=693) it.</sub>

2023-01-25 08:53 UTC, leonardssh approved these changes

2023-01-25 09:10 UTC, Aiuraa commented
@leonardssh how can i review changes if you already aprove it :\

He ask me on discord to review the changes......

2023-01-25 09:25 UTC, leonardssh commented
My approval doesn't prevent you from reviewing. @Aiuraa

2023-01-25 09:32 UTC, GNZTMPZ commented
I still working on translating, i just need some advice though. pls do not merge this, *yet*!

I'll ping a member if it's done. themk :>

2023-01-25 09:46 UTC, Aiuraa commented
> My approval doesn't prevent you from reviewing. @Aiuraa

It does @leonardssh, since i don't updated CODEOWNERS, when someone approved the change the option is not available anymore.

2023-01-25 10:10 UTC, Aiuraa requested changes
Thanks for your contribution!, there is room for improvement that you can do, and also i saw `# Related Function` is not really been translated to indonesian on some places making it inconsistent.

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/BanEx.md
> +Pada versi SA-MP 0.3x, tindakan apa pun yang diambil langsung sebelum Ban() (seperti mengirim pesan dengan SendClientMessage) tidak akan sampai ke player. Timer harus digunakan untuk menunda ban.
> Timer harus digunakan untuk menunda ban.

Gak perlu pakai titik, bisa pakai koma dan tambahkan seperti:
", oleh karena itu timer harus digunakan untuk menunda pelarangan"

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/Kick.md
> +Kick player dari server. Player harus keluar dari game dan re-connect jika mereka masih ingin lanjut bermain.
Deskripsi "Kick" bisa diganti dengan "Tendang"

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/Kick.md
> +| playerid | ID player yang ingin di kick. |
"di kick" bisa diganti menjadi "ditendang"

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/Kick.md
> +        // Kick player yang menggunakan command ini.
Ini juga diganti jadi "Tendang", tidak perlu menggunakan "kick"

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/Kick.md
> +        // Mem-kick player nya sedetik kemudian menggunakan timer.
Komentar ini harusnya bisa diganti menjadi:

"Kemudian, buat sebuah timer untuk menunda fungsi Kick selama sedetik"

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/tolower.md
> +Function ini mengubah sebuah huruf menjadi huruf kecil.
"Function" dapat diubah menjadi "Fungsi"

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/tolower.md
> +- [toupper](toupper)
Deskripsinya jangan lupa.

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/toupper.md
> +- [tolower](tolower)
Deskripsinya jangan lupa

2023-01-25 10:10 UTC, Aiuraa commented on docs/translations/id/scripting/functions/strcmp.md
> +Membanding dua string untuk mengecek apakah mereka sama.
Deskripsinya harusnya sesuai sama yang lain, menggunakan "Fungsi ini", lalu dilanjut dengan "membandingkan kedua string"

2023-01-25 16:27 UTC, GNZTMPZ commented on docs/translations/id/scripting/functions/BanEx.md
> +        // Bans the player who executed this command and includes a reason ("Request")
eh mangap, ini kelupaan 😅

2023-01-25 16:29 UTC, GNZTMPZ commented on docs/translations/id/scripting/functions/tolower.md
> +Function ini mengubah sebuah huruf menjadi huruf kecil.
weird, tp sebenarnya ini udah di fix tauu.. kok masi kek gini?

aneh dah gh 🤔

2023-01-25 16:29 UTC, GNZTMPZ commented on docs/translations/id/scripting/functions/tolower.md
> +- [toupper](toupper)
sebenarnya dr document awalnya gak ada kak, makanya gak dimasukin

namun, klo mau dimasukin yowes tak masukin 👍

2023-01-25 16:29 UTC, GNZTMPZ commented on docs/translations/id/scripting/functions/strcmp.md
> +Membanding dua string untuk mengecek apakah mereka sama.
sebenarnya dr document awalnya gak ada kak, makanya gak dimasukin

namun, klo mau dimasukin yowes tak masukin 👍

2023-01-25 16:30 UTC, GNZTMPZ commented on docs/translations/id/scripting/functions/toupper.md
> +- [tolower](tolower)
sebenarnya dr document awalnya gak ada kak, makanya gak dimasukin

namun, klo mau dimasukin yowes tak masukin 👍

2023-01-26 05:08 UTC, SanityZeroPercent commented
Hey @leonardssh, sorry for bothering you.. 

We really want to help translating documentations and maintain them. Anyway, I've added my name to the CODEOWNERS, but github said that we don't have write access. I wonder if me, along with @Aiuraa and @rsetiawan7 could have the write access if that's possible. 

Thanks.

2023-02-03 05:39 UTC, Aiuraa approved these changes
I think it's good and can be safe to merge, thanks for your contributions though!

2023-02-03 05:57 UTC, rsetiawan7 approved these changes
lgtm

2023-02-03 12:40 UTC, merged

2023-02-03 12:40 UTC, leonardssh commented
Thanks for your contributions!