Added indonesian translation in some pages
openmultiplayer/web pull request #699
Opened 2023-01-21 19:35 UTC by CEKIKOFGAMERS

2023-01-24 09:09 UTC, Aiuraa requested changes
Hello, thanks for contributing but i find there is some room for improvement.

2023-01-24 09:09 UTC, Aiuraa commented on docs/translations/id/scripting/functions/AddSimpleModel.md
> +description: Menambahkan sebuah simple object model untuk didownload.
"diunggah" bukan "didownload"
"model simpel objek" bukan "simple object"

2023-01-24 09:09 UTC, Aiuraa commented on docs/translations/id/scripting/functions/AddSimpleModel.md
> +Menambahkan simple custom object model untuk didownload. Model file bawaanya terletak di Documents\GTA San Andreas User Files\SAMP\cache milik player bernama IP dan PORT dalam bentuk nama CRC.
Harusnya "Menambahkan simple custom object model" menjadi "model simpel kustom objek", lalu juga "didownload" harusnya "diunggah" sesuai KBBI.

Mungkin lebih enak menggunakan `terletak pada folder` dibanding `terletak di`

2023-01-24 09:09 UTC, Aiuraa commented on docs/translations/id/scripting/functions/AddSimpleModel.md
> +## Examples
Kurang spasi

2023-01-24 09:09 UTC, Aiuraa commented on docs/translations/id/scripting/functions/AddSimpleModel.md
> +`useartwork` harus diaktifkan terlebih dahulu dalam pengaturan server agar ini berfungsi Ketika virtualworld diatur, model akan didownload setelah player memasuki world tertentu
"agar ini" dapat dirubah menjadi "agar dapat"

Lalu `Ketika`, `K` nya tidak menggunakan huruf kapital.

2023-01-25 14:11 UTC, CEKIKOFGAMERS commented on docs/translations/id/scripting/functions/AddSimpleModel.md
> +`useartwork` harus diaktifkan terlebih dahulu dalam pengaturan server agar ini berfungsi Ketika virtualworld diatur, model akan didownload setelah player memasuki world tertentu
Baiklah, akan saya perbaiki

2023-02-03 05:37 UTC, Aiuraa approved these changes
I think it's good now, thanks!

2023-02-24 10:54 UTC, merged