Translate
openmultiplayer/web pull request #710
Opened 2023-02-24 21:34 UTC by akos127

2023-02-27 09:49 UTC, Southclaws requested changes
Looks good except this minor issue with the hyperlink and the file path. There's a slight typo in the path name, the word `functions` is spelt `funcitons` which will prevent this page from appearing in the sidebar:

```diff
-docs/translations/hu/scripting/funcitons/SetVehicleAngularVelocity.md
+docs/translations/hu/scripting/functions/SetVehicleAngularVelocity.md
```

2023-02-27 09:49 UTC, Southclaws commented on docs/translations/hu/scripting/funcitons/SetVehicleAngularVelocity.md
> +Ez a függvény a _world_ térben van, nem a _local_ térben. Ha a helyi tér szögsebességét szeretné módosítani, akkor a [jármű rotációs quat] (GetVehicleRotationQuat) alapján elforgatási mátrixot kell a
```suggestion
Ez a függvény a _world_ térben van, nem a _local_ térben. Ha a helyi tér szögsebességét szeretné módosítani, akkor a [jármű rotációs quat](GetVehicleRotationQuat) alapján elforgatási mátrixot kell alkalmaznia.
```

2023-11-29 18:42 UTC, akosd127 reviewed
.

2023-11-29 19:06 UTC, leonardssh approved these changes

2024-01-02 18:07 UTC, akosd127 reviewed
solved

2024-01-03 21:44 UTC, adib-yg approved these changes

2024-01-03 21:48 UTC, merged