added portuguese translation of docs/client/ClientCommands.md file
openmultiplayer/web pull request #72
Opened 2020-12-03 17:47 UTC by joao-pedro-alves

2020-12-03 17:57 UTC, Southclaws approved these changes

2020-12-03 21:22 UTC, joao-pedro-alves commented
Last commit I got a typo in the commit's message. sry

2020-12-03 23:08 UTC, iPollo requested changes
Muito bom! Apenas alguns detalhes a serem corrigidos e um arquivo que foi repetido com o nome de outra **callback**.

2020-12-03 23:08 UTC, iPollo commented on docs/translations/pt/scripting/callbacks/OnPlayerGiveDamageActor.md
> +Esta callback é chamada quando o jogador realiza dano a um ator.
Acredito que "causar" ficaria melhor adaptado. Ex: _"...quando um jogador causa dano a um ator."_ Aplica-se também para as informações abaixo.

2020-12-03 23:08 UTC, iPollo commented on docs/translations/pt/scripting/callbacks/OnPlayerSpawn.md
> +    format(string, sizeof(string), "%s has spawned successfully.", PlayerName);
Pequeno detalhe. Estamos traduzindo também os exemplos em código.

2020-12-03 23:08 UTC, iPollo commented on docs/translations/pt/scripting/callbacks/OnVehicleSirenStateChange.md
> +title: OnVehicleRespray
Acredito que você deve ter copiado e colado para se basear, mas acabou repetindo a mesma callback em outro arquivo.

2020-12-03 23:09 UTC, iPollo commented on docs/translations/pt/scripting/callbacks/OnVehicleSirenStateChange.md
> +title: OnVehicleRespray
O arquivo todo (_OnVehicleRespray_) foi repetido (_OnVehicleSirenStateChange_)

2020-12-04 00:53 UTC, joao-pedro-alves commented
Na verdade as traduções estão apenas sendo compiladas por mim. A maioria está sendo enviada pela galera do portalsamp.com através do multirão que estamos fazendo, então ainda estamos nos organizando em relação a padronização. Hoje mais a noite ou amanhã de manhã reviso os problemas. thx

2020-12-04 13:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/web?pullRequest=72) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/web?pullRequest=72) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/web?pullRequest=72) it.</sub>

2020-12-04 13:17 UTC, joao-pedro-alves commented
@iPollo enviei 3 novos commits com as alterações. Quando puder dar uma olhada ;) Nas próximas contribuições passarei um pente fino e vamos alinhando as padronizações. Em alguns casos existem termos semelhantes com traduções diferentes justamente porque a tradução está sendo feita em conjunto com a comunidade Portal SA-MP mas aos poucos estamos organizando os padrões a seguir :)

2020-12-05 00:01 UTC, iPollo commented
Ótimo trabalho!

2020-12-05 00:01 UTC, merged