Update ClientCommands.md
openmultiplayer/web pull request #758
Opened 2023-08-16 15:19 UTC by DestinyDragon49

Spanish characters corrected

2023-08-24 15:29 UTC, DestinyDragon49 commented
@Southclaws

2024-01-05 22:05 UTC, FreddieCrew requested changes
You need to fix these issues before merging @DestinyDragon49

2024-01-05 22:05 UTC, FreddieCrew commented on docs/translations/es/client/ClientCommands.md
> +| /fontsize      | Cambia el tama&#241;o del texto del UI (chats, di&#225;logos, etc&#233;tera). Valores v&#225;lidos de -3 a 5.
```suggestion
| /fontsize      | Cambia el tamaño del texto del interfaz de usuario (chats, diálogos, etcétera). Valores válidos de -3 a 5.                                                                                                                                                                                                                             |
```

2024-01-05 22:05 UTC, FreddieCrew commented on docs/translations/es/client/ClientCommands.md
>  | /ctd           | Este comando fue agregando en SA:MP 0.3.7 RC2. It enables client debugging of the player camera target.
```suggestion
| /ctd           | Este comando fue agregado en SA:MP 0.3.7 RC2. Habilita la depuración del objetivo de la cámara del jugador.                                                                                                                                                                                                                  |
```

2024-01-05 22:05 UTC, FreddieCrew commented on docs/translations/es/client/ClientCommands.md
> +| /rcon          | Mas relacionado al servidor que al cliente. Este comando es usado para ejecutar comandos RCON. RCON es el sistema de administraci&#243;n integrado. RCON significa [Remote Control](
```suggestion
| /rcon          | Más relacionado al servidor que al cliente. Este comando se usa para ejecutar comandos RCON. RCON es el sistema de administración integrado. RCON significa [Remote Control](../server/ControllingServer#using-rcon).                                                                                                   |
```

2024-01-07 16:17 UTC, adib-yg commented
@FreddieCrew I don't think your changes will fix the unicode error. It's still the same.

![image](https://github.com/openmultiplayer/web/assets/92677767/9522e7a5-3b91-4bf8-8ffe-28a6e3d9e3e5)

2024-01-08 01:14 UTC, FreddieCrew commented
@adib-yg I just tried it on my localhost, and it seems to be working perfectly fine.

![screenshot](https://github.com/openmultiplayer/web/assets/120303127/6be7d966-6032-4680-a8b8-e6cb0273f90a)

2024-01-08 10:19 UTC, merged