Translated several docs to Indonesian
openmultiplayer/web pull request #763
Opened 2023-09-01 05:28 UTC by xJoww

Translated several following documents:
- OnPlayerEnterRaceCheckpoint
- OnPlayerLeaveRaceCheckpoint
- OnPlayerLeaveCheckpoint
- OnUnoccupiedVehicleUpdate
- OnTrailerUpdate

2023-09-19 19:36 UTC, ohmypxl commented
Sorry i forgot to look this, i'll start reviewing stuff

2023-09-19 19:47 UTC, ohmypxl requested changes
Hai, terimakasih telah membantu open.mp untuk menerjemahkan fungsi dan callback yang tersedia kedalam bahasa indonesia, namun ada beberapa hal yang mungkin bisa di perbaiki sebelum nantinya bisa di gabungkan kedalam branch.

2023-09-19 19:47 UTC, ohmypxl commented on docs/translations/id/scripting/callbacks/OnTrailerUpdate.md
> +- [OnUnoccupiedVehicleUpdate](../callbacks/OnUnoccupiedVehicleUpdate.md): Callback ini dipanggil ketika posisi kendaraan tanpa pengemudi disinkronkan oleh klien.
Ini juga sama

2023-09-19 19:47 UTC, ohmypxl commented on docs/translations/id/scripting/callbacks/OnUnoccupiedVehicleUpdate.md
> +- [OnTrailerUpdate](../callbacks/OnTrailerUpdate.md): Dipanggil ketika posisi trailer disinkronkan oleh klien.
`Dipanggil` bisa diganti menjadi `Terpanggil`

2023-09-19 19:47 UTC, ohmypxl commented on docs/translations/id/scripting/functions/DestroyObject.md
> +- [AttachPlayerObjectToPlayer](AttachPlayerObjectToPlayer): Menempelkan Objek pemain ke Pemain lain.
Masih ada beberapa kesalahan kecil khususnya pada bagian `Ojek` dan `Pemain`. Seharusnya disesuaikan dengan mengunakan huruf kecil.

2023-09-19 19:47 UTC, ohmypxl commented on docs/translations/id/scripting/functions/DestroyObject.md
> +| objectid | ID dari Objek yang akan dihapus. Dikembalikan oleh CreateObject. |
`Objek` bisa menggunakan huruf kecil semua.

2023-09-19 19:47 UTC, ohmypxl commented on docs/translations/id/scripting/callbacks/OnPlayerLeaveRaceCheckpoint.md
> +- [OnPlayerEnterRaceCheckpoint](../callbacks/OnPlayerEnterRaceCheckpoint.md): Callback ini terpanggil jika pemain memasuki sebuah checkpoint balapan.
Inipun juga sama seperti diatas

2023-09-19 19:47 UTC, ohmypxl commented on docs/translations/id/scripting/callbacks/OnPlayerLeaveCheckpoint.md
> +- [OnPlayerLeaveRaceCheckpoint](../callbacks/OnPlayerLeaveRaceCheckpoint.md): Callback ini terpanggil jika pemain meninggalkan sebuah checkpoint balapan.
Ini juga, bisa di hapus `Callback ini`

2023-09-19 19:47 UTC, ohmypxl commented on docs/translations/id/scripting/callbacks/OnPlayerEnterRaceCheckpoint.md
> +- [OnPlayerLeaveRaceCheckpoint](../callbacks/OnPlayerLeaveRaceCheckpoint.md): Callback ini terpanggil jika pemain meninggalkan sebuah checkpoint balapan.
Lebih baik dihapus `Callback ini` agar supaya lebih enak di lihat dan terlihat sama dengan fungsi terkait.

2024-01-03 22:06 UTC, adib-yg commented
@xJoww Want to apply these changes? Otherwise, PR will be closed.

2024-01-06 19:05 UTC, adib-yg commented
I'm closing the PR because @xJoww isn't even active. I also not sure about applying ohmypxl changes by myself.

You can request to reopen the PR in the future or just open a new one.

2024-01-06 19:05 UTC, closed without merging