Translation for PT-BR
openmultiplayer/web pull request #774
Opened 2023-10-09 04:45 UTC by CarlinCV

2023-10-09 04:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/web?pullRequest=774) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/web?pullRequest=774) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/web?pullRequest=774) it.</sub>

2023-10-09 08:33 UTC, Southclaws commented on DestroyObject.md
> +description: Destr�i (remove) um objeto que foi criado usando CreateObject.
looks like unicode errors here
```suggestion
description: Destrói (remove) um objeto que foi criado usando CreateObject.

```

2023-10-09 08:33 UTC, Southclaws commented on DestroyObject.md
> +description: Destr�i (remove) um objeto que foi criado usando CreateObject.
looks like unicode errors here
```suggestion
description: Destrói (remove) um objeto que foi criado usando CreateObject.

```

2023-10-09 08:33 UTC, Southclaws commented on DestroyObject.md
> +## Descri��o
```suggestion
## Descrição

```

2023-10-09 08:34 UTC, Southclaws requested changes
looks good but we need to fix those unicode errors

2023-10-13 23:18 UTC, iPollo approved these changes

2024-01-04 11:35 UTC, adib-yg approved these changes

2024-01-04 11:39 UTC, merged