Fix download button tooltip and change SA-MP client download button title
openmultiplayer/web pull request #785
Opened 2023-11-22 15:04 UTC by FreddieCrew

The title says it all, I also added SA-MP client download button to the "Ready to get started?" section.

2023-11-22 15:11 UTC, leonardssh approved these changes

2023-11-22 15:12 UTC, AmyrAhmady requested changes

2023-11-22 15:35 UTC, FreddieCrew commented on frontend/src/pages/index.tsx
> +        title={props.title}
Now it's working as an actual reusable tooltip. Can I mark this conversation as resolved, or is there anything else?

2023-11-22 15:36 UTC, FreddieCrew commented on frontend/src/pages/index.tsx
> +                  <DownloadButton
Ok, removed the button at the bottom.

2023-11-22 15:37 UTC, FreddieCrew commented on frontend/src/pages/index.tsx
> -                    title={"Download SA-MP client"}
Reverted the title to just 'SA-MP client'.

2023-12-08 23:13 UTC, AmyrAhmady approved these changes

2023-12-08 23:13 UTC, merged