Translate more docs in to Bosnian.
openmultiplayer/web pull request #856
Opened 2024-01-21 19:11 UTC by NermanLegacy

Translated the following `Resources` documents:
- anglemodes.md
- boneid.md
- bullethittypes.md
- callbacks-sequence.md
- cameracutstyles.md
- cameramodes.md
- clicksources.md
- Componentslots.md
- spectatetypes.md
- recordtypes.md

Translated the following `Client` document:
- sa-mp.cfg.md

Translated the following `Tutorials` document:
- PortForwarding.md

2024-01-21 19:11 UTC, NermanLegacy commented
@adib-yg @daddyDOT If there are any problems please let me know. Thanks in advance.

2024-01-21 21:04 UTC, adib-yg requested changes

2024-01-21 21:04 UTC, adib-yg commented on docs/scripting/functions/SetPlayerMarkerForPlayer.md
> +- [GetPlayerMarkerForPlayer](GetPlayerMarkerForPlayer): Gets a player's marker for a specific player.
```suggestion
- [GetPlayerMarkerForPlayer](GetPlayerMarkerForPlayer): Gets the colour of a player's nametag and radar blip for another player.
```

2024-01-22 12:46 UTC, adib-yg approved these changes

2024-01-22 18:22 UTC, daddyDOT requested changes
Sve dobro, samo pregledaj i ispravi ovo gdje sam ostavio komentar na "`kapija`".

2024-01-22 18:22 UTC, daddyDOT commented on docs/translations/bs/tutorials/PortForwarding.md
> +Ok, evo početka, počnite pronalaženjem svog **kapija**. Pretpostavimo da imate vista. Kliknite na start, kliknite na polje za pretragu i napišite **cmd**. Tada se pojavljuje crna kutija. Unesite slje
Kapija? 😅
Ostavi 'gateway-a'

2024-01-23 10:21 UTC, NermanLegacy reviewed
@daddyDOT Ispravio sam gresku.

2024-01-23 16:33 UTC, daddyDOT approved these changes

2024-01-23 16:33 UTC, merged