Update GetPlayerAnimationFlags.md, added code sample and a warning
openmultiplayer/web pull request #874
Opened 2024-02-05 19:20 UTC by m0b-x

2024-02-05 19:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/web?pullRequest=874) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/web?pullRequest=874) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/web?pullRequest=874) it.</sub>

2024-02-06 00:24 UTC, FreddieCrew reviewed
Looks good to me, except for line 19, which has a small "typo".

> Returns the player animation flags as integer

It's missing the "an" article.

We can take advantage of this pull request and fix this "typo" already.

2024-02-06 15:04 UTC, adib-yg commented
I tested the code and it doesn't work
Or possibly the function is broken. It's not even included in omp-stdlib.

<details>
<summary>Screenshots</summary>

![sa-mp-170](https://github.com/openmultiplayer/web/assets/92677767/b52e4cd8-f177-4923-ba6e-79562a3a290f)

![sa-mp-171](https://github.com/openmultiplayer/web/assets/92677767/55e846ee-b4b2-4a58-891f-d93a60de1988)

</details>

2024-02-06 15:35 UTC, m0b-x commented
Does it work if you add this to your gamemode? 
```c

native GetPlayerAnimFlags(playerid);

```

![sa-mp-009](https://github.com/openmultiplayer/web/assets/72597190/83616445-506a-4072-a77f-1f688f3a856c)

2024-02-06 17:07 UTC, adib-yg requested changes

2024-02-06 17:07 UTC, adib-yg commented on docs/scripting/functions/GetPlayerAnimationFlags.md
> +        new flags = GetPlayerAnimFlags(playerid);
```suggestion
        new flags = GetPlayerAnimationFlags(playerid);
```

2024-02-06 17:07 UTC, adib-yg commented on docs/scripting/functions/GetPlayerAnimationFlags.md
> +        format(messageString, sizeof(messageString), "You anim flags are: [freeze:%i] [lockx:%i] [locky:%i] [loop:%i]", freeze, lockx, locky, loop);
```suggestion
        format(messageString, sizeof(messageString), "Your anim flags are: [freeze:%i] [lockx:%i] [locky:%i] [loop:%i]", freeze, lockx, locky, loop);
```

2024-02-06 17:07 UTC, adib-yg commented on docs/scripting/functions/GetPlayerAnimationFlags.md
> +If the player is in a vehicle, all returned animation flags are 0.
```suggestion
If the player state is not on-foot, all returned animation flags are 0.
```

2024-02-06 17:07 UTC, adib-yg commented on docs/scripting/functions/GetPlayerAnimationFlags.md
```suggestion

## Notes

```

2024-02-07 13:13 UTC, merged