Translate main pages
openmultiplayer/web pull request #984
Opened 2024-04-06 02:36 UTC by ulasbayraktar

2024-04-06 22:05 UTC, adib-yg requested changes
I found several issues.

```json
"server-sumbitted": "serverCodeHn} is added to our pending list. If it's not available after maximum 48 hours, you can contact us on Discord!",
```

**Missing {**  `"serverCodeHn}`

<hr />

```json
"Partners (BETA TESTERS)" : "Partnerler (BETA TESTERLER)",
```

`"Partnerler (BETA TESTERLER)"` is Turkish and it repeated in all translation files.

<hr />

```json
"Documentation": "Documentatio",
```

`Documentatio` spelling mistake.

<hr />

```json
"IP/Domain": "AIP/Domain",
```

`AIP` to `IP`

<hr />

```json
"Change language from English": "Change language from English",
```

It doesn't need the name of the language.

```tsx
<ModalHeader>{translateText(locale, "General", `Change language from ${getLanguageName(locale)}`)}</ModalHeader>
```

So just:

```json
"Change language from ": "Change language from ",
```

2024-04-07 13:48 UTC, ulasbayraktar commented
@adib-yg 

> ```json
> "Change language from English": "Change language from English",
> ```
> 
> It doesn't need the name of the language.
> 
> ```tsx
> <ModalHeader>{translateText(locale, "General", `Change language from ${getLanguageName(locale)}`)}</ModalHeader>
> ```
> 
> So just:
> 
> ```json
> "Change language from ": "Change language from ",
> ```

We need the name of the language because the place of words is not the same in all languages. Example

Change language from **English**
Dili **Türkçe** dilinden değiştir.


As you can see, the name of the language in another language is in the middle of the sentence, while in another language it is at the end of the sentence.

2024-04-08 02:23 UTC, adib-yg commented
I come to the conclusion that this is not good.

1. The keys are very long. Isn't this better?

```json
"Index": {
  "Getting Started": "Getting started",
  "Fully backwards compatible with existing scripts and clients": "Fully backwards compatible with existing scripts and clients",
  
  "index-text-1": "Getting started",
  "index-text-2": "Fully backwards compatible with existing scripts and clients",
```

Or like this: https://github.com/openmultiplayer/launcher/blob/master/src/locales/translations/en.ts

2. Announcements are temporary and old announcement remain in files after replacement. It will be difficult to remove them in the future.

But please don't make any changes for now, let other team members decide.

2024-04-11 11:18 UTC, ulasbayraktar commented
Barnaby had already said that it should be like this @AmyrAhmady

2025-01-18 10:52 UTC, ulasbayraktar commented
any news?

2025-01-18 13:54 UTC, closed without merging